### ISSUE TITLE
Add Tooltip for the delete icon

### ISSUE THREAD

**Issue by vivekiet22** [vivekiet22/package_search#11]
we can add tooltip for delete icon like this
![image](https://user-images.githubusercontent.com/57106245/226878010-ef308675-8573-48dc-9544-38384ea96223.png)

**Comment by vivekiet22** [comment]
hi @shyamtawli 
Take your time and complete it :)

**Comment by shyamtawli** [comment]
@vivekiet22 Can you guide me into adding two data-toggle in single element.
I have find a way to add Delete tooltip from bootstrap but I have to add "data-toggle: "tooltip" and the delete icon already contains one data-toggle:"modal".

**Comment by vivekiet22** [comment]
@shyamtawli you can wrap the icon in a span and add `data-toggle` and `title` to it.
You can refer to this [documentation](https://getbootstrap.com/docs/4.0/components/tooltips/#disabled-elements)

**Comment by shyamtawli** [comment]
Thanks @vivekiet22 . I am not familiar with bootstrap but find a way and I am adding `data-toggle` on same element but you share the document and it really helped.
