### ISSUE TITLE
Add the icons 

### ISSUE THREAD

**Issue by vivekiet22** [vivekiet22/package_search#5]
Add the icons to `view the favorite` and `edit the favorite `

**Comment by Fuji-P** [comment]
hi @vivekiet22 
Could you provide me with your preferred icon?
・[View](https://fontawesome.com/v4/icon/eye)
・[Edit](https://fontawesome.com/v4/icon/pencil-square-o)

**Comment by vivekiet22** [comment]
@Fuji-P 
Both the `View` and `Edit` icons look good to me. You can add those.

**Comment by vivekiet22** [comment]
this issue has been solved #12
