### ISSUE TITLE
Add functionality of edit icon

### ISSUE THREAD

**Issue by vivekiet22** [vivekiet22/package_search#6]
after solving issue #5 we can add the functionality of the edit button.When clicked we can edit the package details.

**Comment by Fuji-P** [comment]
@vivekiet22 
Could you please provide a detailed summary of the feature requirements you would like to add in this issue?
Specifically, what information should be displayed and what behavior are you hoping for?

**Comment by vivekiet22** [comment]
@Fuji-P  , We can do something like this-when we click on the edit icon it opens a form containing two inputs.
first input labeled `package name and the other with `why is it your favorite`.
using this we can update the package details

**Comment by Fuji-P** [comment]
@vivekiet22 
Sure, could you please provide a rough sketch or image of the screen you have in mind, even if it's a simple one?

**Comment by vivekiet22** [comment]
Hey, since we are using bootstrap.we can refer to [this](https://getbootstrap.com/docs/4.0/components/modal/#live-demo)
