### ISSUE TITLE
add functionality of view icon button

### ISSUE THREAD

**Issue by vivekiet22** [vivekiet22/package_search#7]
after solving issue #5 we can add the functionality of the view icon button.When clicked we can see the package details.

**Comment by Fuji-P** [comment]
@vivekiet22 
Could you please provide a detailed summary of the feature requirements you would like to add in this issue?
Specifically, what information should be displayed and what behavior are you hoping for?

**Comment by vivekiet22** [comment]
@Fuji-P , when the user clicks on this icon it shows the package name in a popup.
Additionally we can store the `why is it your fav`  and display it in the pop up

**Comment by Fuji-P** [comment]
@vivekiet22 
Sure, could you please provide a rough sketch or image of the screen you have in mind, even if it's a simple one?

**Comment by vivekiet22** [comment]
Hey, since we are using bootstrap. we can refer to [this](https://getbootstrap.com/docs/4.0/components/modal/#live-demo)
When clicking it will show package details
